#!/usr/bin/perl
# copyright (c) 2016 Mitsuhiko Sato. All Rights Reserved.
# Mitsuhiko Sato ( E-mail: mitsuhikoevolution@gmail.com )
use strict;
use warnings;
use Getopt::Long;

my $verbose;

GetOptions('verbose|v' => \$verbose);

die "USAGE: count_character [--verbose|-v] file.fasta one_char(e.g. -, N)\n" if(@ARGV != 2);     

open(IN,$ARGV[0]) or die "$!";
if($ARGV[0] =~ /\.gz$/){
    close(IN);
    open(IN,"gzip -dc $ARGV[0] |") or die "$!";
}

my $char=$ARGV[1];

my %seqs;
my $gene_name;
while (my $line=<IN>){
    chomp($line);
    if($line =~ /^>(\S+)/){
        $gene_name=$1;
        $seqs{$gene_name}=0;
    }else{
        while($line =~ m/$char/g){
            $seqs{$gene_name}++;
        }
    }
}
close(IN);

my $total=0;
foreach my $chrom(sort (keys %seqs) ){
    $total=$total+$seqs{$chrom};
    print "$chrom\t$seqs{$chrom}\n" if($verbose);
}
print "$ARGV[0]\ttotal\t$total\n";
